POST https://api-node-0yc2.onrender.com/videos
Content-Type: application/json 

{
    "title": "node",
    "description": "Este e o primeiro video",
    "duration": 110
}

### 

GET https://api-node-0yc2.onrender.com/videos
// https://api-node-0yc2.onrender.com/videos?search=node 


###

PUT https://api-node-0yc2.onrender.com/videos/52c23418-0b6b-4b62-878f-07cd330225f7
Content-Type: application/json 

{
    "title": "node",
    "description": "Este não é o primeiro video",
    "duration": 900
}


###

DELETE https://api-node-0yc2.onrender.com/videos/
###